// icons
import atleticIcon from '/public/images/main/matches/atletic.png'
import atleticoIcon from '/public/images/main/matches/atletico.png'
import barcaIcon from '/public/images/main/matches/barca.png'
import leipzigIcon from '/public/images/main/matches/leipzig.png'
import liverpoolIcon from '/public/images/main/matches/liverpool.png'
import marcelIcon from '/public/images/main/matches/marcel.png'
import psjIcon from '/public/images/main/matches/psj.png'
import rennaisIcon from '/public/images/main/matches/rennais.png'

export const matches = {
    todayMatches: [
        {
            id: 'todayMatchesGame1',
            date: '20:00',
            gameState: '.rowOne.gameState.started',
            teamOne: '.rowOne.teamOne',
            teamOneIcon: atleticIcon.src,
            score: '2 : 1',
            teamTwo: '.rowOne.teamTwo',
            teamTwoIcon: atleticoIcon.src,
            buyButtonName: '.rowOne.buyButton',
            titleName: '.rowOne.title',
        },
        {
            id: 'todayMatchesGame2',
            date: '21:30',
            gameState: '.rowTwo.gameState.dontStarted',
            teamOne: '.rowTwo.teamOne',
            teamOneIcon: barcaIcon.src,
            score: '-',
            teamTwo: '.rowTwo.teamTwo',
            teamTwoIcon: psjIcon.src,
            buyButtonName: '.rowTwo.buyButton',
            titleName: '.rowTwo.title',
        },
        {
            id: 'todayMatchesGame3',
            date: '22:20',
            gameState: '.rowThree.gameState.dontStarted',
            teamOne: '.rowThree.teamOne',
            teamOneIcon: marcelIcon.src,
            score: '-',
            teamTwo: '.rowThree.teamTwo',
            teamTwoIcon: rennaisIcon.src,
            buyButtonName: '.rowThree.buyButton',
            titleName: '.rowThree.title',
        },
        {
            id: 'todayMatchesGame4',
            date: '23:30',
            gameState: '.rowFore.gameState.dontStarted',
            teamOne: '.rowFore.teamOne',
            teamOneIcon: liverpoolIcon.src,
            score: '-',
            teamTwo: '.rowFore.teamTwo',
            teamTwoIcon: leipzigIcon.src,
            buyButtonName: '.rowFore.buyButton',
            titleName: '.rowFore.title',
        },
        {
            id: 'todayMatchesGame5',
            date: '20:00',
            gameState: '.rowOne.gameState.dontStarted',
            teamOne: '.rowOne.teamOne',
            teamOneIcon: atleticIcon.src,
            score: '-',
            teamTwo: '.rowOne.teamTwo',
            teamTwoIcon: atleticoIcon.src,
            buyButtonName: '.rowOne.buyButton',
            titleName: '.rowOne.title',
        },
        {
            id: 'todayMatchesGame6',
            date: '21:30',
            gameState: '.rowTwo.gameState.dontStarted',
            teamOne: '.rowTwo.teamOne',
            teamOneIcon: barcaIcon.src,
            score: '-',
            teamTwo: '.rowTwo.teamTwo',
            teamTwoIcon: psjIcon.src,
            buyButtonName: '.rowTwo.buyButton',
            titleName: '.rowTwo.title',
        },
        {
            id: 'todayMatchesGame7',
            date: '22:20',
            gameState: '.rowThree.gameState.dontStarted',
            teamOne: '.rowThree.teamOne',
            teamOneIcon: marcelIcon.src,
            score: '-',
            teamTwo: '.rowThree.teamTwo',
            teamTwoIcon: rennaisIcon.src,
            buyButtonName: '.rowThree.buyButton',
            titleName: '.rowThree.title',
        },
        {
            id: 'todayMatchesGame8',
            date: '23:30',
            gameState: '.rowFore.gameState.dontStarted',
            teamOne: '.rowFore.teamOne',
            teamOneIcon: liverpoolIcon.src,
            score: '-',
            teamTwo: '.rowFore.teamTwo',
            teamTwoIcon: leipzigIcon.src,
            buyButtonName: '.rowFore.buyButton',
            titleName: '.rowFore.title',
        }
    ],
    tommorowMatches: [
        {
            id: 'todayMatchesGame1',
            date: '20:00',
            gameState: '.rowOne.gameState.started',
            teamOne: '.rowOne.teamOne',
            teamOneIcon: atleticIcon.src,
            score: '2 : 1',
            teamTwo: '.rowOne.teamTwo',
            teamTwoIcon: atleticoIcon.src,
            buyButtonName: '.rowOne.buyButton',
            titleName: '.rowOne.title',
        },
        {
            id: 'todayMatchesGame2',
            date: '21:30',
            gameState: '.rowTwo.gameState.dontStarted',
            teamOne: '.rowTwo.teamOne',
            teamOneIcon: barcaIcon.src,
            score: '-',
            teamTwo: '.rowTwo.teamTwo',
            teamTwoIcon: psjIcon.src,
            buyButtonName: '.rowTwo.buyButton',
            titleName: '.rowTwo.title',
        },
        {
            id: 'todayMatchesGame3',
            date: '22:20',
            gameState: '.rowThree.gameState.dontStarted',
            teamOne: '.rowThree.teamOne',
            teamOneIcon: marcelIcon.src,
            score: '-',
            teamTwo: '.rowThree.teamTwo',
            teamTwoIcon: rennaisIcon.src,
            buyButtonName: '.rowThree.buyButton',
            titleName: '.rowThree.title',
        },
        {
            id: 'todayMatchesGame4',
            date: '23:30',
            gameState: '.rowFore.gameState.dontStarted',
            teamOne: '.rowFore.teamOne',
            teamOneIcon: liverpoolIcon.src,
            score: '-',
            teamTwo: '.rowFore.teamTwo',
            teamTwoIcon: leipzigIcon.src,
            buyButtonName: '.rowFore.buyButton',
            titleName: '.rowFore.title',
        },
        {
            id: 'todayMatchesGame5',
            date: '20:00',
            gameState: '.rowOne.gameState.dontStarted',
            teamOne: '.rowOne.teamOne',
            teamOneIcon: atleticIcon.src,
            score: '-',
            teamTwo: '.rowOne.teamTwo',
            teamTwoIcon: atleticoIcon.src,
            buyButtonName: '.rowOne.buyButton',
            titleName: '.rowOne.title',
        },
        {
            id: 'todayMatchesGame6',
            date: '21:30',
            gameState: '.rowTwo.gameState.dontStarted',
            teamOne: '.rowTwo.teamOne',
            teamOneIcon: barcaIcon.src,
            score: '-',
            teamTwo: '.rowTwo.teamTwo',
            teamTwoIcon: psjIcon.src,
            buyButtonName: '.rowTwo.buyButton',
            titleName: '.rowTwo.title',
        },
        {
            id: 'todayMatchesGame7',
            date: '22:20',
            gameState: '.rowThree.gameState.dontStarted',
            teamOne: '.rowThree.teamOne',
            teamOneIcon: marcelIcon.src,
            score: '-',
            teamTwo: '.rowThree.teamTwo',
            teamTwoIcon: rennaisIcon.src,
            buyButtonName: '.rowThree.buyButton',
            titleName: '.rowThree.title',
        },
        {
            id: 'todayMatchesGame8',
            date: '23:30',
            gameState: '.rowFore.gameState.dontStarted',
            teamOne: '.rowFore.teamOne',
            teamOneIcon: liverpoolIcon.src,
            score: '-',
            teamTwo: '.rowFore.teamTwo',
            teamTwoIcon: leipzigIcon.src,
            buyButtonName: '.rowFore.buyButton',
            titleName: '.rowFore.title',
        }
    ]
}