// icons
import atleticIcon from '/public/images/main/matches/atletic.png'
import atleticoIcon from '/public/images/main/matches/atletico.png'
import barcaIcon from '/public/images/main/matches/barca.png'
import leipzigIcon from '/public/images/main/matches/leipzig.png'
import liverpoolIcon from '/public/images/main/matches/liverpool.png'
import marcelIcon from '/public/images/main/matches/marcel.png'
import psjIcon from '/public/images/main/matches/psj.png'
import rennaisIcon from '/public/images/main/matches/rennais.png'

export const matches = {
    todayMatches: [
        {
            id: 'todayMatchesGame1',
            date: '20:00',
            time: '22:30',
            gameState: '.rowOne.gameState.started',
            teamOneName: 'Атлетико',
            teamOneIcon: atleticIcon.src,
            score: '2 : 1',
            teamTwoName: 'Атлетик',
            teamTwoIcon: atleticoIcon.src,
            buyButtonName: '.rowOne.buyButton',
            coefficent: '1.67',
            titleName: '.rowOne.title',
        },
        {
            id: 'todayMatchesGame2',
            date: '21:30',
            time: '22:30',
            gameState: '.rowTwo.gameState.dontStarted',
            teamOneName: 'Барселона',
            teamOneIcon: barcaIcon.src,
            score: '-',
            teamTwoName: 'ПСЖ',
            teamTwoIcon: psjIcon.src,
            buyButtonName: '.rowTwo.buyButton',
            coefficent: '1.67',
            titleName: '.rowTwo.title',
        },
        {
            id: 'todayMatchesGame3',
            date: '22:20',
            time: '22:30',
            gameState: '.rowThree.gameState.dontStarted',
            teamOneName: 'Марсель',
            teamOneIcon: marcelIcon.src,
            score: '-',
            teamTwoName: 'Атлетик',
            teamTwoIcon: rennaisIcon.src,
            buyButtonName: '.rowThree.buyButton',
            coefficent: '1.67',
            titleName: '.rowThree.title',
        },
        {
            id: 'todayMatchesGame4',
            date: '23:30',
            time: '22:30',
            gameState: '.rowFore.gameState.dontStarted',
            teamOneName: 'Атлетико',
            teamOneIcon: liverpoolIcon.src,
            score: '-',
            teamTwoName: 'Атлетик',
            teamTwoIcon: leipzigIcon.src,
            buyButtonName: '.rowFore.buyButton',
            coefficent: '1.67',
            titleName: '.rowFore.title',
        },
        {
            id: 'todayMatchesGame5',
            date: '20:00',
            time: '22:30',
            gameState: '.rowOne.gameState.dontStarted',
            teamOneName: 'Атлетико',
            teamOneIcon: atleticIcon.src,
            score: '-',
            teamTwoName: 'Атлетик',
            teamTwoIcon: atleticoIcon.src,
            buyButtonName: '.rowOne.buyButton',
            coefficent: '1.67',
            titleName: '.rowOne.title',
        },
        {
            id: 'todayMatchesGame6',
            date: '21:30',
            time: '22:30',
            gameState: '.rowTwo.gameState.dontStarted',
            teamOneName: 'Атлетико',
            teamOneIcon: barcaIcon.src,
            score: '-',
            teamTwoName: 'Атлетик',
            teamTwoIcon: psjIcon.src,
            buyButtonName: '.rowTwo.buyButton',
            coefficent: '1.67',
            titleName: '.rowTwo.title',
        },
        {
            id: 'todayMatchesGame7',
            date: '22:20',
            time: '22:30',
            gameState: '.rowThree.gameState.dontStarted',
            teamOneName: 'Атлетико',
            teamOneIcon: marcelIcon.src,
            score: '-',
            teamTwoName: 'Атлетик',
            teamTwoIcon: rennaisIcon.src,
            buyButtonName: '.rowThree.buyButton',
            coefficent: '1.67',
            titleName: '.rowThree.title',
        },
        {
            id: 'todayMatchesGame8',
            date: '23:30',
            time: '22:30',
            gameState: '.rowFore.gameState.dontStarted',
            teamOneName: 'Атлетико',
            teamOneIcon: liverpoolIcon.src,
            score: '-',
            teamTwoName: 'Атлетик',
            teamTwoIcon: leipzigIcon.src,
            buyButtonName: '.rowFore.buyButton',
            coefficent: '1.67',
            titleName: '.rowFore.title',
        }
    ],
    tommorowMatches: [
        {
            id: 'todayMatchesGame1',
            date: '20:00',
            time: '22:30',
            gameState: '.rowOne.gameState.started',
            teamOneName: 'Атлетико',
            teamOneIcon: atleticIcon.src,
            score: '2 : 1',
            teamTwoName: 'Атлетик',
            teamTwoIcon: atleticoIcon.src,
            buyButtonName: '.rowOne.buyButton',
            coefficent: '1.67',
            titleName: '.rowOne.title',
        },
        {
            id: 'todayMatchesGame2',
            date: '21:30',
            time: '22:30',
            gameState: '.rowTwo.gameState.dontStarted',
            teamOneName: 'Атлетико',
            teamOneIcon: barcaIcon.src,
            score: '-',
            teamTwoName: 'Атлетик',
            teamTwoIcon: psjIcon.src,
            buyButtonName: '.rowTwo.buyButton',
            coefficent: '1.67',
            titleName: '.rowTwo.title',
        },
        {
            id: 'todayMatchesGame3',
            date: '22:20',
            time: '22:30',
            gameState: '.rowThree.gameState.dontStarted',
            teamOneName: 'Атлетико',
            teamOneIcon: marcelIcon.src,
            score: '-',
            teamTwoName: 'Атлетик',
            teamTwoIcon: rennaisIcon.src,
            buyButtonName: '.rowThree.buyButton',
            coefficent: '1.67',
            titleName: '.rowThree.title',
        },
        {
            id: 'todayMatchesGame4',
            date: '23:30',
            time: '22:30',
            gameState: '.rowFore.gameState.dontStarted',
            teamOneName: 'Атлетико',
            teamOneIcon: liverpoolIcon.src,
            score: '-',
            teamTwoName: 'Атлетик',
            teamTwoIcon: leipzigIcon.src,
            buyButtonName: '.rowFore.buyButton',
            coefficent: '1.67',
            titleName: '.rowFore.title',
        },
        {
            id: 'todayMatchesGame5',
            date: '20:00',
            time: '22:30',
            gameState: '.rowOne.gameState.dontStarted',
            teamOneName: 'Атлетико',
            teamOneIcon: atleticIcon.src,
            score: '-',
            teamTwoName: 'Атлетик',
            teamTwoIcon: atleticoIcon.src,
            buyButtonName: '.rowOne.buyButton',
            coefficent: '1.67',
            titleName: '.rowOne.title',
        },
        {
            id: 'todayMatchesGame6',
            date: '21:30',
            time: '22:30',
            gameState: '.rowTwo.gameState.dontStarted',
            teamOneName: 'Атлетико',
            teamOneIcon: barcaIcon.src,
            score: '-',
            teamTwoName: 'Атлетик',
            teamTwoIcon: psjIcon.src,
            buyButtonName: '.rowTwo.buyButton',
            coefficent: '1.67',
            titleName: '.rowTwo.title',
        },
        {
            id: 'todayMatchesGame7',
            date: '22:20',
            time: '22:30',
            gameState: '.rowThree.gameState.dontStarted',
            teamOneName: 'Атлетико',
            teamOneIcon: marcelIcon.src,
            score: '-',
            teamTwoName: 'Атлетик',
            teamTwoIcon: rennaisIcon.src,
            buyButtonName: '.rowThree.buyButton',
            coefficent: '1.67',
            titleName: '.rowThree.title',
        },
        {
            id: 'todayMatchesGame8',
            date: '23:30',
            time: '22:30',
            gameState: '.rowFore.gameState.dontStarted',
            teamOneName: 'Атлетико',
            teamOneIcon: liverpoolIcon.src,
            score: '-',
            teamTwoName: 'Атлетик',
            teamTwoIcon: leipzigIcon.src,
            buyButtonName: '.rowFore.buyButton',
            coefficent: '1.67',
            titleName: '.rowFore.title',
        }
    ]
}